---
title: "India Sociolinguistics Geographic Associations Analyses"
author: "Ruthe Foushee"
date: "2023-08-18"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r origins-setup, include=FALSE}
library(here)
here::i_am('1_speaker-associations/1a_geographic-origin.Rmd')

knitr::opts_chunk$set(
  echo = FALSE, message=F, warning=F,
  fig.width = 6)

source(here('isl-resources.R'))
```

```{r read-in-data}
a <- read.csv(here('data/r_dfs/associations_data.csv'))[,-1]

factor_vars <- c('study_name', 'id', 'child_sex', 'child_religion', 
                 'school', 'standard',
                 'question_type', 'language', 'speaker_gender', 
                 'origin', 'geographic_origin', 'religion', 'wealth',
                 'army_navy_language')

numeric_vars <- c('standard_num', 'child_age', 'child_age_centered', 
                  'sequence', 'coded_wealth')

a <- a %>%
  mutate_at(factor_vars, as.factor) %>%
  mutate_at(numeric_vars, as.numeric)

g <- a %>%
  filter(origin!="")
```

```{r origin-no-opinion-trials}
N_TRIALS <- g %>%
  filter(no_opinion_geo==1) %>%
  summarize(no_opinion_trials=n()) %>%
  as.numeric()

N_CHILDREN <- g %>%
  filter(no_opinion_geo==1) %>%
  group_by(id) %>%
  summarize(no_opinion_trials=n()) %>%
  summarize(n_children=n()) %>%
  as.numeric()
  
g %>%
  filter(no_opinion_geo==1) %>%
  group_by(id)%>%
  summarize(no_opinion_trials=n()) %>%
  group_by(no_opinion_trials) %>%
  summarize(n_children=n()) %>%
  kable(.)

g %>%
  filter(no_opinion_geo==1) %>%
  group_by(language)%>%
  summarize(n=n()) %>%
  arrange(desc(n)) %>%
  kable(.)

# 39 trials opted out from 27 children, most for chinese/tamil
```

"No opinion" selected on `r N_TRIALS` trials by `r N_CHILDREN` children; all children selected single response.

```{r origin-overall-barplot, include=F}
geographic_summary_tab <- g %>%
  ungroup(.) %>%
  dplyr::select("language", all_of(origin_vars)) %>%
  gather(., origin, selection, -language) %>%
    group_by(language, origin) %>%
    summarize(mean=na.mean(selection),
              cilo = mean-ci.low(selection),
              cihi = mean+ci.high(selection)) 

geographic_summary_tab$origin <- factor(
  geographic_summary_tab$origin, 
  levels=origin_vars, 
  labels=origin_labels)

ggplot(geographic_summary_tab, 
       aes(x=origin, y=mean, fill=origin)) +
    geom_bar(stat="identity") + 
    geom_errorbar(aes(ymin=cilo, ymax=cihi), width=0, 
                  color=line_color) + 
    facet_wrap(~language, ncol=2) +
    scale_fill_manual(values = origin_colors, origin_legend_title1) +
    ylim(0, 1) +
    sans_theme +
    theme(legend.title = element_text(
      size=10, colour="gray30", family="sans", face="italic")) +
    ylab("Mean") 

ggsave("geographic_associations.png", device = "png", 
       path = "plots/speaker-associations/",
       scale = 1, width = 7, height = 6, units = "in")
```

## By Standard

```{r origin-std-lineplot}
geographic_std_summary_tab <- g %>%
  ungroup(.) %>%
  dplyr::select("language", "standard", "standard_num",
    all_of(origin_vars)) %>%
  gather(., origin, selection, -language, -standard, -standard_num) %>%
    group_by(language, standard, standard_num, origin) %>%
    summarize(mean=na.mean(selection),
              cilo = mean-ci.low(selection),
              cihi = mean+ci.high(selection)) 

geographic_std_summary_tab$origin <- factor(
  geographic_std_summary_tab$origin, 
  levels=origin_vars, 
  labels=origin_labels)

ggplot(geographic_std_summary_tab, 
       aes(x=standard_num, y=mean, color=origin)) +
    geom_line(aes(lty=origin)) + 
    geom_point(aes(shape=origin)) +
    geom_errorbar(aes(ymin=cilo, ymax=cihi), width=0) +
    facet_wrap(~language, ncol=4) +
    scale_color_manual(values=origin_colors, origin_legend_title) + 
    scale_shape_manual(values=origin_shapes, origin_legend_title) +
    scale_linetype_manual(values=origin_ltys, origin_legend_title) +
    ylim(0, 1) +
    scale_x_continuous(breaks=c(1, 2, 3), label=std_axis_labels) +
   # labs(title="Geographic Associations Across Standards 3-7") +
    sans_axes_theme +
    theme(legend.position = "bottom") +
    xlab("Grade") +
    ylab("Mean")
  
ggsave("geographic_origin_std.png", device = "png", 
       path = "plots/final/",
       scale = 1, width = 7, height = 5, units = "in")

ggsave("geographic_origin_std.png", device = "png", 
       path = "plots/speaker-associations/",
       scale = 1, width = 7, height = 5, units = "in")
```

```{r origin-std-barplot, include=F}

ggplot(geographic_std_summary_tab[
  !is.na(geographic_std_summary_tab$language),], 
       aes(x=origin, y=mean, fill=origin)) +
    geom_bar(stat="identity") + 
    geom_errorbar(aes(ymin=cilo, ymax=cihi), width=0, 
                  color=line_color) + 
    facet_wrap(~language + standard, ncol=3) +
    scale_fill_manual(values = origin_colors, origin_legend_title1) +
    ylim(0, 1) +
    xlab("Standard") +
    ylab("Mean") +
    sans_axes_theme +
    theme(legend.title = element_text(
      size=10, colour="gray30", family="sans", face="italic"))

ggsave("plots/geographic_origin_std_barplot.png", height=16, width=14, units="in")
```

## With Age

```{r origin-age, include=F}
geographic_age_df <- g %>%
  ungroup(.) %>%
  dplyr::select(
    "language", "child_age_centered", all_of(origin_vars)) %>%
  gather(., origin, selection, -language, -child_age_centered) 

geographic_age_df$origin <- factor(geographic_age_df$origin, 
      levels=origin_vars, labels=origin_labels)

ggplot(geographic_age_df, 
       aes(x=child_age_centered, y=selection, color=origin, lty=origin, fill=origin)) +
    stat_smooth(aes(x=child_age_centered, y=selection), 
                method="lm", level=.75, fullrange=T) +
    facet_wrap(~language, ncol=4) +
    scale_color_manual(values = origin_colors, origin_legend_title1) +
    scale_linetype_manual(values=origin_ltys, origin_legend_title1) +
    scale_fill_manual(values=origin_colors, origin_legend_title1) +
    ylim(0, 1) +
    ylab("Mean") +
    xlab("Child Age (yrs)") +
    #labs(title="Geographic Associations with Age") +
    sans_axes_theme +
    theme(legend.title = element_text(
      size=10, colour="gray30", family="sans", face="italic"))

ggsave("geographic_age_lm.png", device = "png", 
       path = "plots/",
       scale = 1, width = 7, height = 6, units = "in")
```

## Models

### Odds of Origin Selection

#### Gujarat (Same place as me)  

```{r gujarat-glm}
ass_gujarat_glm <- glm(
  gujarat ~ child_age_centered + language, 
  family="binomial", g)

cbind(round(exp(coef(ass_gujarat_glm)), 2),
round(exp(confint(ass_gujarat_glm)), 2)) %>%
  kable(.)
```

```{r gujarat-int-glm}
ass_gujarat_int_glm <- glm(
  gujarat ~ child_age_centered*language, 
  family="binomial", g)

cbind(round(exp(coef(ass_gujarat_int_glm)), 2),
round(exp(confint(ass_gujarat_int_glm)), 2))%>%
  kable(.)

Anova(ass_gujarat_int_glm)
# sig interaction
```

#### Another part of India (A different city)  

```{r india-glm}
ass_india_glm <- glm(
  india ~ child_age_centered + language, 
  family="binomial", g)

cbind(round(exp(coef(ass_india_glm)), 2),
round(exp(confint(ass_india_glm)), 2))%>%
  kable(.)
```

```{r india-int-glm}
ass_india_int_glm <- glm(
  india ~ child_age_centered*language, 
  family="binomial", g)

cbind(round(exp(coef(ass_india_int_glm)), 2),
round(exp(confint(ass_india_int_glm)), 2))%>%
  kable(.)

Anova(ass_india_int_glm)
# n.s. interaction
```

#### Outside India (Foreign)  

```{r foreign-glm}
ass_foreign_glm <- glm(
  foreign ~ child_age_centered + language, 
  family="binomial", g)

cbind(round(exp(coef(ass_foreign_glm)), 2),
round(exp(confint(ass_foreign_glm)), 2))%>%
  kable(.)
```

```{r foreign-int-glm}
ass_foreign_int_glm <- glm(
  foreign ~ child_age_centered*language, 
  family="binomial", g)

cbind(round(exp(coef(ass_foreign_int_glm)), 2),
round(exp(confint(ass_foreign_int_glm)), 2))%>%
  kable(.)

Anova(ass_foreign_int_glm)
# sig interaction
```

### Mixed Effects Multinomial Regression  

```{r geo-mblogit, warning=F}
g_for_plots <- g %>% filter(origin!="idk",
                           origin!="")
g_for_plots$origin <- relevel(g_for_plots$origin, ref="Gujarat")
g_for_plots$origin_labeled <- plyr::mapvalues(g_for_plots$origin,
                                             from=c("Gujarat",
                                                    "India",
                                                    "foreign"),
                                             to=c("Gujarat (Same place as me)",
                                                  "Another state in India",
                                                  "Outside India (foreign)"))


g_for_plots$language <- relevel(g_for_plots$language, ref="Gujarati")
g_for_plots$age <- g_for_plots$child_age_centered

geo_mod <- mblogit(origin_labeled ~ language*age,
                   random=~1|id,
                   g_for_plots) # dropping idks

summary(geo_mod)
```

```{r geo-mblogit-plot}
sjPlot::plot_model(geo_mod) +
  theme_blank() +
  theme(strip.text = element_text(color="gray30", size=12, face="bold")) +
 # theme(panel.grid.major.y=element_line(color="gray80")) +
  geom_hline(yintercept=1, lty=2, color="gray50") +
  scale_color_manual(values=c("#fc8d59", "#99d594")) +
  labs(title="Geographic Origin: This speaker is from...")
  #theme(plot.background = element_rect(fill=NA))

ggsave("geo_mod_with_age_interaction.png", device = "png", 
       path = "plots/forest_plots/",
       scale = 1, width = 7, height = 6, units = "in")
```

```{r geomod-table}
sjPlot::tab_model(geo_mod)

#library(rrtable)
#library(xtable)
#HTMLcode2latex(sjPlot::tab_model(geo_mod)$knitr)

#sjPlot::tab_model(geo_mod)$knitr %>%
#  kable(format="latex") %>%
#  xtable(.) %>% print(., filen="geo_tab.tex")
```

```{r geo-mblogit-simple-plot, warning=F}
# add subtitle: relative to being from gujarat, this speaker is from...
geo_mod_no_int <- mblogit(origin_labeled ~ 0 + language + age,
                   random=~1|id,
                   g_for_plots) # dropping idks

p <- sjPlot::plot_model(geo_mod_no_int) +
  #theme_blank() +
  theme(strip.text = element_text(color="gray30", size=12, face="bold")) +
 # theme(panel.grid.major.y=element_line(color="gray80")) +
  geom_hline(yintercept=1, lty=2, color="gray50") +
  scale_color_manual(values=c("#fc8d59", "#99d594")) +
  labs(title="Geographic Origin: This speaker is from...")
  #theme(plot.background = element_rect(fill=NA))

# add gridlines and reduce axis to cap out at 100

ggsave("geo_mod_just_age.png", device = "png", 
       path = "plots/forest_plots/",
       scale = 1, width = 7, height = 6, units = "in")
```

```{r}
g_n <- g_for_plots %>%
  group_by(origin_labeled, language) %>%
  summarize(n=n())

g_n$facet <- g_n$origin_labeled
g_n$term <- g_n$language
p$data$term <- gsub("language", "", p$data$term)
p$data <- merge(p$data, g_n[c("term", "facet", "n")], 
                by=c("facet", "term"))
p$data$term <- levels(c(language_labels, "age"))

p + geom_point(aes(size=n)) 

#problem is with 
```

```{r}
p$data$term <- fct_rev(p$data$term)
p + geom_point(aes(size=n)) #+
  #ylim(0.01, 50)
# make error bars a different color/shade and in front of circle
# circle representing size can be outline not filled

#problem is with 
```

```{r geo-id-mblogit, warning=F}
i <- read.csv(here('data/language_identification_correct.csv'))

gi <- merge(g_for_plots, i, by=c("language", "id"))

geo_id_mod <- mblogit(origin_labeled ~ language*id_correct + age,
                   random=~1|id,
                   data = gi)
summary(geo_id_mod)
```

```{r geo-mblogit-id-plot}

sjPlot::plot_model(geo_id_mod) +
  theme_blank() +
  theme(strip.text = element_text(color="gray30", size=12, face="bold")) +
 # theme(panel.grid.major.y=element_line(color="gray80")) +
  geom_hline(yintercept=1, lty=2, color="gray50") +
  scale_color_manual(values=c("#fc8d59", "#99d594")) +
  labs(title="Geographic Origin: This speaker is from...")
  #theme(plot.background = element_rect(fill=NA))

ggsave("geo_mod_with_id_interaction.png", device = "png", 
       path = "plots/forest_plots/",
       scale = 1, width = 7, height = 6, units = "in")
```

```{r geomod-id-table}
sjPlot::tab_model(geo_id_mod)
```